### ISSUE TITLE
Submit to packagist

### ISSUE THREAD

**Issue by SamuelMwangiW** [zacksmash/fortify-spa#1]
Hey @zacksmash.

Kudos for the amazing work on this package.
Running `composer require zacksmash/fortify-spa` does not work at the moment. 
This is probably because you've just recently created the repository but this is a time savior: thanks.
To test I added the following to my composer.json:
```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/zacksmash/fortify-spa"
        }
    ],
```

**Comment by zacksmash** [comment]
Oh, gosh! Sorry about that. I've submitted it to Packagist. Would you mind giving it a try to see if it works now?

**Comment by SamuelMwangiW** [comment]
Works like a charm. Thanks for the fast response
